services:
  novamusic-frontend:
    image: daronenko/novamusic-frontend:${VERSION}
    container_name: novamusic-frontend
    build:
      dockerfile: docker/Dockerfile
      context: ..
    env_file: .env
    ports:
      - 3000:3000
    restart: on-failure
