services:
  novamusic-frontend:
    image: daronenko/novamusic-frontend:${VERSION}
    container_name: novamusic-frontend
    build:
      dockerfile: docker/Dockerfile
      context: ..
    env_file: .env
    ports:
      - 443:${PORT}
    restart: on-failure
    volumes:
      - /etc/ssl/nova-music.ru:/etc/ssl/nova-music.ru
