name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
    steps:
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Check out code into directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload build result
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist

  delivery:
    name: Delivery
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist
      
      - name: Transfer build files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 185.241.194.24
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          source: "dist/*"
          target: "/var/www/nova-music/dist"
          strip_components: 1